export const FETCH_EMPLOYEES_STARTED = "FETCH_EMPLOYEES_STARTED";
export const FETCH_EMPLOYEES_SUCCEEDED = "FETCH_EMPLOYEES_SUCCEEDED";
export const FETCH_EMPLOYEES_FAILED = "FETCH_EMPLOYEES_FAILED";

export const FAKE_LOGOUT = "FAKE_LOGOUT";
export const FAKE_LOGIN = "FAKE_LOGIN";
export const SAVE_ADDRESS = "SAVE_ADDRESS";
