export const FETCH_EMPLOYEES_STARTED = "FETCH_EMPLOYEES_STARTED";
export const FETCH_EMPLOYEES_SUCCEEDED = "FETCH_EMPLOYEES_SUCCEEDED";
export const FETCH_EMPLOYEES_FAILED = "FETCH_EMPLOYEES_FAILED";
