export const FETCH_EMPLOYEES_STARTED = "FETCH_EMPLOYEES_STARTED";
export const FETCH_EMPLOYEES_SUCCEEDED = "FETCH_EMPLOYEES_SUCCEEDED";
export const FETCH_EMPLOYEES_FAILED = "FETCH_EMPLOYEES_FAILED";

export const FAKE_LOGOUT = "FAKE_LOGOUT";
export const FAKE_LOGIN = "FAKE_LOGIN";
export const SAVE_ADDRESS = "SAVE_ADDRESS";

export const SEND_EMPLOYEE_STARTED = "SEND_EMPLOYEE_STARTED";
export const SEND_EMPLOYEE_SUCCEEDED = "SEND_EMPLOYEE_SUCCEEDED";
export const SEND_EMPLOYEE_FAILED = "SEND_EMPLOYEE_FAILED";
